---
networks:
  frontend:
    external: true
services:
  homeassistant:
    container_name: homeassistant-prod-1
    image: "ghcr.io/home-assistant/home-assistant:2024.8.3"
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/ttyACMO
    privileged: true
    labels:
      traefik.enable: "true"
      traefik.http.services.homeassistant-prod-1.loadbalancer.server.port: "8123"
      traefik.http.services.homeassistant-prod-1.loadbalancer.server.scheme: "http"
      traefik.http.routers.homeassistant-prod-1-https.entrypoints: "websecure"
      traefik.http.routers.homeassistant-prod-1-https.rule: "Host(`homeassistant-prod-1.srv-prod-7.home.clcreative.de`)"
      traefik.http.routers.homeassistant-prod-1-https.tls: "true"
      traefik.http.routers.homeassistant-prod-1-https.tls.certresolver: "cloudflare"
    networks:
      - frontend
    restart: unless-stopped
